FROM golang:alpine AS builder
WORKDIR /go/src/github.com/lordvidex/gomoney
COPY ./server ./server
COPY ./pkg ./pkg
COPY go.mod go.sum ./
RUN go build -o /go/bin/gomoney-server ./server/cmd

FROM alpine:latest AS production
COPY --from=builder /go/bin/gomoney-server /go/bin/gomoney-server
EXPOSE 8080
ENTRYPOINT ["/go/bin/gomoney-server"]