FROM golang:1.18 AS development
WORKDIR /go/src/github.com/lordvidex/gomoney
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go install github.com/cespare/reflex@latest
CMD reflex -sr '\.go$' go run ./telegram/cmd/main.go

FROM golang:alpine AS builder
WORKDIR /go/src/github.com/lordvidex/gomoney
COPY ./telegram ./telegram
COPY ./pkg ./pkg
COPY go.mod go.sum ./
RUN go build -o /go/bin/gomoney-telegram ./telegram/cmd

FROM alpine:latest AS production
COPY --from=builder /go/bin/gomoney-telegram /go/bin/gomoney-telegram
ENTRYPOINT ["/go/bin/gomoney-telegram"]
