FROM golang:alpine AS builder
WORKDIR /go/src/github.com/lordvidex/gomoney
COPY ./telegram ./telegram
COPY ./pkg ./pkg
COPY go.mod go.sum ./
RUN go build -o /go/bin/gomoney-telegram ./telegram/cmd

FROM alpine:latest AS production
COPY --from=builder /go/bin/gomoney-telegram /go/bin/gomoney-telegram
EXPOSE 8080
ENTRYPOINT ["/go/bin/gomoney-telegram"]
