FROM golang:1.18 AS development
WORKDIR /go/src/github.com/lordvidex/gomoney-api
COPY ./api ./api
COPY ./pkg ./pkg
COPY go.mod go.sum ./
RUN go mod download
RUN go install github.com/cespare/reflex@latest
EXPOSE 8080
CMD reflex -sr '\.go$' go run ./api/cmd/main.go

FROM golang:alpine AS builder
WORKDIR /go/src/github.com/lordvidex/gomoney-api
COPY ./api ./api
COPY ./pkg ./pkg
COPY go.mod go.sum ./
RUN go build -o /go/bin/gomoney-api api/cmd/main.go

FROM alpine:latest AS production
COPY --from=builder /go/bin/gomoney-api /go/bin/gomoney-api
EXPOSE 8080
ENTRYPOINT ["/go/bin/gomoney-api"]
