version: '3.8'

services:
  db:
    container_name: "gomoney-db" 
    image: postgres:latest
    restart: always
    env_file:
      - ./db.env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "gomoney"]
      interval: 10s
      timeout: 30s
      retries: 5

  server-dev:
    container_name: "gomoney-grpc-server"
    volumes:
      - ./server:/go/src/github.com/lordvidex/gomoney/server
    environment:
      - DATABASE_URL=${DATABASE_URL}
    build:
      dockerfile: deployments/Dockerfile-server
      target: development
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8002:8080"
        
  
  api:
    container_name: "gomoney-api-server"
    volumes:
      - ./api:/go/src/github.com/lordvidex/gomoney-api/api
    environment:
      - GRPC_SERVER=server-dev:8080
    build: 
      dockerfile: deployments/Dockerfile-api
      target: development
    depends_on:
      - server-dev
    ports:
      - "8000:8080"

  telegram:
    container_name: "gomoney-telegram-server"
    build:
      dockerfile: deployments/Dockerfile.telegram
    ports:
      - "8001:8080"

volumes:
  db: