version: '3.8'

services:
  db:
    container_name: "gomoney-db" 
    image: postgres:latest
    restart: always
    env_file:
      - ./db.env
    ports:
      - "5432:5432"
    volumes:
        - db:/var/lib/postgresql/data
        - ./scripts/multiple-database.sh:/docker-entrypoint-initdb.d/multiple-database.sh
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "gomoney"]
      interval: 10s
      timeout: 30s
      retries: 5

  redis-db:
    container_name: "gomoney-redis"
    image: redis:latest
    restart: always
    command: >
      --requirepass ${REDIS_PASSWORD}
    env_file:
      - ./db.env
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 5

  server-dev:
    container_name: "gomoney-grpc-server"
    volumes:
      - .:/go/src/github.com/lordvidex/gomoney
    environment:
      - DATABASE_URL=${DATABASE_URL}
    build:
      dockerfile: deployments/Dockerfile-server
      target: development
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8002:8080"
      - "8003:8081"

  api:
    container_name: "gomoney-api-server"
    volumes:
      - .:/go/src/github.com/lordvidex/gomoney-api/
    environment:
      - GRPC_SERVER=server-dev:8080
      - REDIS_URL=${REDIS_URL}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    build: 
      dockerfile: deployments/Dockerfile-api
      target: development
    depends_on:
      redis-db:
        condition: service_healthy
    ports:
      - "8000:8080"

  telegram:
    container_name: "gomoney-telegram-server"
    environment:
      - GRPC_SERVER=server-dev:8080
      - REDIS_URL=${REDIS_URL}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - .:/go/src/github.com/lordvidex/gomoney/
    build:
      dockerfile: deployments/Dockerfile-telegram
      target: development
    depends_on:
      redis-db:
        condition: service_healthy

volumes:
  db:
  redis: